name: Setup Rust
description: Setup Rust
inputs:
  target:
    description: toolchain target triple
    required: false
runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.74.0

    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev # libgtk-3-dev is used by rfd
        version: 1.0
        execute_install_scripts: true

    - uses: FedericoCarboni/setup-ffmpeg@v2

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: build-cache
