name: Setup Rust
description: Setup Rust
inputs:
  target:
    description: toolchain target triple
    required: false
runs:
  using: 'composite'
  steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.74.0

    - name: Install dependencies
      uses: ConorMacBride/install-package@v1
      with:
        brew: pkg-config ffmpeg
        apt: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev clang libavcodec-dev libavformat-dev libavfilter-dev libavutil-dev libavdevice-dev pkg-config
        choco: ffmpeg

    - name: Install LLVM and Clang
      if: runner.os == 'Windows'
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: 16

    - name: run-vcpkg
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
            

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: build-cache
