name: Build project

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-latest
    name: Build ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev # libgtk-3-dev is used by rfd
          version: 1.0
          execute_install_scripts: true

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-cache

      - name: Check build
        run: cargo check --locked
